### PR TITLE
Add deployment scripts

### PR DESCRIPTION
**Pull request by glib-briia**
TODO: 

- codesigning.asc.enc needs to be generated and added
- $TO_BE_PROVIDED_key -iv $TO_BE_PROVIDED_iv to be replaced with the correct variables names in before-deploy.sh
- secure: TO_BE_PROVIDED= - to be replaced with generated values in travis.yml

### CODE REVIEW

**Comment by glib-briia** [comment]
Hi @mpkorstanje , could you please take a look when you get some time.

**Comment by mpkorstanje** [comment]
@glib-briia I've merged this so because you created this branch in your own fork. Feel free to create any future branches in this repo.

**Comment by mpkorstanje** [comment]
Now to setup the credentials.

**Comment by mpkorstanje** [comment]
@glib-briia all done. I've added a [RELEASING.md](https://github.com/cucumber/cucumber-jvm-scala/blob/master/RELEASING.md) guide. Please give it a try.

**Pull request merged**
