### PR TITLE
upgraded to 2.4.0 and removed scala 2.10 support

### PR DESCRIPTION
**Pull request by akhil**

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Thanks for the PR. I don’t think we have a maintainer for this project at the moment: https://cucumber.io/blog/2018/05/19/cucumber-jvm-languages-support

Would you be interested to take this over? All you need to do is merge/reject other PRs and mke the occasional release.

**Comment by aslakhellesoy** [comment]
#7 muat be fixed before this can be merged

**Comment by jakzal** [comment]
@akhil the build should be triggered now once you rebase with master

**Comment by jakzal** [comment]
I updated this PR with the following:
* merge master branch in
* no longer build with scala 2.10 on the CI
* only execute examples with the latest scala version - the examples module depends on scala_2.12 module. I missed this when setting up the CI. 

Build is green.

**Comment by mpkorstanje** [comment]
@jakzal 

I can't help you make a release right now.  Too busy at the moment. Maybe next week.

Aslaks question does apply to you too btw.

**Comment by jakzal** [comment]
No worries, thanks for the review!

**Comment by jakzal** [comment]
As for taking over. I'm up for bringing this repo up to date with the latest cucumber-jvm. I could help with releases once I learn how they're done ;)

I'm new to cucumber's codebase though and currently learning my way around it ;)

**Comment by aslakhellesoy** [comment]
Hi @akhil,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by mpkorstanje** [comment]
Hop into slack, people might be able to answer some questions.

**Comment by akhil** [comment]
I began to use new java8 cucumber in my scala project. I am not sure if this lib would have much value in its current form.

**Pull request merged**
